---
- name: Inlcude tasks for basic configuration
  include_tasks: configure_basic.yml

- name: Inlcude tasks to configure authentication
  include_tasks: configure_auth.yml

- name: Inlcude tasks to configure ssl
  include_tasks: configure_ssl.yml

- name: Configure mailbox locations and namespaces
  ansible.builtin.template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot service

- name: Configure mailboxes
  ansible.builtin.template:
    src: 15-mailboxes.conf.j2
    dest: /etc/dovecot/conf.d/15-mailboxes.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot service

- name: Configure services
  ansible.builtin.template:
    src: 10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot service

- name: Configure imap
  ansible.builtin.template:
    src: 20-imap.conf.j2
    dest: /etc/dovecot/conf.d/20-imap.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot service

- name: Inlcude tasks to configure lda
  include_tasks: configure_lda.yml

- name: Inlcude tasks to configure managesieve
  include_tasks: configure_managesieve.yml
