---
- name: Inlcude tasks for basic configuration
  include_tasks: configure_basic.yml

- name: Inlcude tasks to configure authentication
  include_tasks: configure_auth.yml

- name: Inlcude tasks to configure ssl
  include_tasks: configure_ssl.yml

- name: Configure mailbox locations and namespaces
  ansible.builtin.template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot service

- name: Inlcude tasks to configure lda
  include_tasks: configure_lda.yml

- name: Configure managesieve
  ansible.builtin.template:
    src: 20-managesieve.conf.j2
    dest: /etc/dovecot/conf.d/20-managesieve.conf
    owner: root
    group: root
    mode: '0644'
  when: dovecot_managesieve|bool
  notify: Restart dovecot service
