---
- name: "Set protocols"
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    create: true
    regexp: "protocols = "
    line: "protocols = {{ dovecot_protocols }}"
    owner: root
    group: root
    mode: '0644'
  when: dovecot_protocols|length >0
  notify: Restart dovecot service
