---
- name: Inlcude tasks for basic configuration
  include_tasks: configure_basic.yml

- name: Inlcude tasks to configure authentication
  include_tasks: configure_auth.yml

- name: Inlcude tasks to configure ssl
  include_tasks: configure_ssl.yml

