---
- name: Include tasks to install dovecot
  ansible.builtin.include_tasks: install.yml

- name: Include tasks to configure dovecot
  ansible.builtin.include_tasks: configure.yml

- name: Enable and start dovecot service
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true
