---
- name: Inlcude tasks to install dovecot
  include_tasks: install.yml

- name: Inlcude tasks to configure dovecot
  include_tasks: configure.yml

- name: Enable and start dovecot service
  service:
    name: dovecot
    state: started
    enabled: true
