---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather service facts
      service_facts:

    - debug:
        var: ansible_facts.services["dovecot.service"]

    - name: Check dovecot service state
      fail:
        msg: The service dovecot is not running.
      when: ansible_facts.services["dovecot.service"].state != "running"

    - name: Check dovecot service state
      fail:
        msg: The service dovecot is not enabled.
      when: ansible_facts.services["dovecot.service"].status != "enabled"
